version: "2"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "9030:9030"
      - "9090:9090"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
